
CREATE TABLE role(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT,
	active TINYINT DEFAULT 0,
	deletable TINYINT DEFAULT 1,
	roleId INT DEFAULT 3,
	username VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255),
	firstName VARCHAR(255) DEFAULT NULL,
	lastName VARCHAR(255) DEFAULT NULL,
	email VARCHAR(255) DEFAULT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_USER2ROLE_1 FOREIGN KEY (roleId) REFERENCES role (id),
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

COMMIT;

INSERT INTO role (id,name) VALUES (1,'Admin');
INSERT INTO role (id,name) VALUES (2,'Employee');
INSERT INTO role (id,name) VALUES (3,'Customer');
INSERT INTO users (id,username,password,active,roleId,deletable) VALUES (1,'admin', 'password', 1,1,0);

CREATE TABLE account(
	id INT NOT NULL AUTO_INCREMENT,
	userId INT NOT NULL,
	accountNumber INT UNIQUE NOT NULL,
	balance INT DEFAULT 0,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_USER2ACCOUNT_1 FOREIGN KEY (userId) REFERENCES users (id),
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE transaction(
	id INT NOT NULL AUTO_INCREMENT,
	accountId INT NOT NULL,
	transactionType INT NOT NULL,
	amount INT NOT NULL,
	balance INT NOT NULL,
	description VARCHAR(255) NOT NULL,
	dateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_ACCOUNT2TRANSACTION_1 FOREIGN KEY (accountId) REFERENCES account (id),
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;